# Add a service for each of the two AI 

services:
    main:
        build: ./main
        ports:
          - "80:5000"
    ai1:
        build: ./ai1
        expose:
          - "5000"
        ports:
          - "81:5000"
    ai2:
        build: ./ai2
        expose:
          - "5000"
        ports:
          - "82:5000"

